services:
  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME:-mysql_database}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-black_box_db}
      MYSQL_USER: ${DB_USER:-local_dev}
      MYSQL_PASSWORD: ${DB_PASSWORD:-rootpassword}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
